### ISSUE TITLE
Fix router version in readme.md

### ISSUE THREAD

**Issue by 0xoldhu** [connext/nxtp-router-docker-compose#14]
![image](https://user-images.githubusercontent.com/105863049/169699148-506e5dee-868d-40a6-9855-f3859e300eea.png)

From [readme](https://github.com/connext/nxtp-router-docker-compose#run-docker-compose-stack) the router_version still links to [images](https://github.com/connext/nxtp/pkgs/container/nxtp-router). But from the [docs](https://docs.connext.network/routers/spinning-up) it points to [release page](https://github.com/connext/nxtp/releases). So it needs to be fixed to help routers set up the latest release version.

**Comment by dharmendrakariya** [comment]
also there is discrepancy in docker image name, in docker-compose its coming from here [ghcr.io/connext/router:latest](https://github.com/connext/nxtp/pkgs/container/router) while in docs as you said it mentions from [ghcr.io/connext/nxtp-router:latest](https://github.com/connext/nxtp/pkgs/container/nxtp-router)

**Comment by rhlsthrm** [comment]
> also there is discrepancy in docker image name, in docker-compose its coming from here [ghcr.io/connext/router:latest](https://github.com/connext/nxtp/pkgs/container/router) while in docs as you said it mentions from [ghcr.io/connext/nxtp-router:latest](https://github.com/connext/nxtp/pkgs/container/nxtp-router)

This discrepancy is coming from the legacy -> amarok change. The `legacy` branch reflects the old versions.
